#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: [push, pull_request]

env:
  PR_IMAGE_TAG: pr-${{ github.event.number }}

jobs:
  set-pr-number:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set PR number
        if: github.event_name == 'pull_request'
        env:
          GIT_COMMITTER_NAME: ${{ github.event.pull_request.user.login }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref ${{ github.head_ref }})
          REMOTE_BRANCH_EXISTS=$(git ls-remote --heads origin "pr-number-${BRANCH_NAME}")
          git config --local user.name "${{ env.GIT_COMMITTER_NAME }}"
          git config --local user.email "${{ env.GIT_COMMITTER_EMAIL }}"
          mkdir -p ./shared-files
          if [[ -z "${REMOTE_BRANCH_EXISTS}" ]]; then
            git checkout -b "pr-number-${BRANCH_NAME}"
            echo -n "PR_IMAGE_TAG=${{ env.PR_IMAGE_TAG }}" > ./shared-files/pr-image-tag
            git add ./shared-files/pr-image-tag
            git commit -m "Set PR_IMAGE_TAG"
            git push origin HEAD:pr-number-${BRANCH_NAME}
          else
            git checkout "pr-number-${BRANCH_NAME}"
            if [ -f ./shared-files/pr-image-tag ] && [[ $(cat ./shared-files/pr-image-tag) == *"pr-${{ github.event.number }}"* ]]; then
                echo "File already exists with correct value. Skipping write."
                exit 0
            fi
          fi
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check all properties have description
        run: ./check_properties_description.sh
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
